14 get clean data for specified period
42association/server_with_m5 pull request #18
Opened 2024-04-05 11:36 UTC by Sawawa42

This PR is to resolve https://github.com/42association/server_with_m5/issues/14 .

2024-04-05 11:52 UTC, ShotaTanemura requested changes
- [x] DB関連の処理を実行している部分は`db.go`に関数にまとめて移す
- [ ] Activityを`cleaning`roleかどうかでフィルタリングする

2024-04-07 01:00 UTC, kotto5 commented
db 関係のmethod は gorm 使うので要らなくなりそう?
ただ、sql の勉強にはなるのでtry 自体はいいと思います!

2024-04-07 09:45 UTC, Sawawa42 commented
> db 関係のmethod は gorm 使うので要らなくなりそう? ただ、sql の勉強にはなるのでtry 自体はいいと思います!

Gormを使うとしても流れは一緒なのでコードを流用するつもりです

2024-04-08 13:16 UTC, Sawawa42 commented
- Preload()を用いて先に関連テーブルを読み込むことでデータを取得できるように修正
- Find()を用いて構造体の配列に直接スライスを入れ、rowsでのループを廃止した
- Joinsでテーブルを結合して読み込む前に時間で絞り込みを行うように順序を変更し、負荷を減らした。

2024-04-09 04:58 UTC, ShotaTanemura commented on src/server/main.go
> +	Activitys, err := getCleanData(c, db)
すごく細かいですが、`Activity`の複数形は`Activities`なので変数名変えましょう

2024-04-09 04:58 UTC, ShotaTanemura commented on src/server/go.mod
このファイルですが`main`ブランチにあるものの方が正しいように思われるのでコミットから外すか、再度`go mod tidy`を実行して、変更をコミットしてもらえると助かります

2024-04-09 04:58 UTC, ShotaTanemura commented on src/server/go.sum
このファイルですが`main`ブランチにあるものの方が正しいように思われるのでコミットから外すか、再度`go mod tidy`を実行して、変更をコミットしてもらえると助かります

2024-04-09 04:58 UTC, ShotaTanemura commented on src/server/db.go
> +func getCleanData(c *gin.Context, db *gorm.DB) ([]Activity, error) {
`func getCleanData(c *gin.Context, db *gorm.DB) ([]Activity, error)`の中でクエリの取り出すをせずに、クエリの取り出しは呼び出し元で実施し、この関数には取り出したパラメーターを渡すようにしていただきたいです！
理由として、この関数の処理内容がDBへの操作だけでなくHTTPリクエスト処理もしないといけなくなってしまった結果、1角関数が担う処理が`get clean data`するだけではなくなってしまっているからです...
その結果、例えば、DBの操作をスル関すであるのにも関わらず、136行目などでエラー時にレスポンスを詰める処理までしてしまっています...
また、`cleaning`のデータを取ること以外にも使えると便利だなと思ったので、関数のプロトタイプ都市低下のようなものにするのはいかがでしょうか！？
`func getCleanData(start int, end int, type string, db *gorm.DB) ([]Activity, error)`
ご検討よろしくおねがいします！！

2024-04-09 07:30 UTC, ShotaTanemura approved these changes
![](https://raw.githubusercontent.com/colons/lgtm-template/master/gifs/nichijou2.gif)

2024-04-09 07:30 UTC, merged